name = input("Enter your Name:")
branch = input("\nEnter your Branch:")
gender = input("\nEnter your Gender:")
college = input("\nEnter your College:")
age = input("\nEnter your Age:")

print("\n\nYour name is:",name)
print("\nYour branch is:",branch)
print("\nYour gender is:",gender)
print("\nYour college is:",college)
print("\nYour age is:",age)
